import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Colors, Spacing, FontFamily, FontSize, BorderRadius } from '../../theme';

export function AIDisclaimer() {
  return (
    <View style={styles.container}>
      <MaterialCommunityIcons
        name="robot-outline"
        size={20}
        color={Colors.primary}
        style={styles.icon}
      />
      <View style={styles.textContainer}>
        <Text style={styles.title}>AI-Generated Summary</Text>
        <Text style={styles.description}>
          This interpretation is generated by AI for informational purposes only and does not
          replace professional medical advice. Always consult a licensed healthcare provider for a
          formal diagnosis.
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    backgroundColor: Colors.tertiary, // Soft blue background
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: 'rgba(6, 113, 171, 0.2)', // Slightly darker border using primary color
    marginVertical: Spacing.md,
  },
  icon: {
    marginRight: Spacing.sm,
    marginTop: 2,
  },
  textContainer: {
    flex: 1,
  },
  title: {
    fontFamily: FontFamily.bold,
    fontSize: FontSize.sm,
    color: Colors.primary,
    marginBottom: 4,
  },
  description: {
    fontFamily: FontFamily.regular,
    fontSize: FontSize.xs,
    color: Colors.textSecondary,
    lineHeight: 18,
  },
});
